export const POKECOLOR = {
  'bug': 'LawnGreen',
  'dark': 'DimGrey',
  'poison': 'DarkViolet',
  'electric': 'Gold',
  'dragon': 'DarkSlateBlue',
  'fairy': 'violet',
  'fighting': 'Crimson',
  'fire': 'OrangeRed',
  'flying': 'SteelBlue',
  'ghost': 'indigo',
  'grass': 'DarkGreen',
  'ground': 'DarkGoldenrod',
  'ice': 'Cyan',
  'normal': 'Goldenrod',
  'psychic': 'DeepPink',
  'rock': 'Peru',
  'steel': 'Silver',
  'water': 'RoyalBlue'
}
